/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AuthorisedEntity { 
    /**
     * Name of the authorised entity
     */
    name: string;
    /**
     * Name of the financial institution through which the direct debit will be executed
     */
    financialInstitution: string;
    /**
     * Australian Business Number for the authorised entity
     */
    abn?: string;
    /**
     * Australian Business Number for the authorised entity
     */
    acn?: string;
    /**
     * Australian Registered Body Number for the authorised entity
     */
    arbn?: string;
}