/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreditCardAccount { 
    /**
     * The minimum payment amount due for the next card payment
     */
    minPaymentAmount: string;
    /**
     * The amount due for the next card payment
     */
    paymentDueAmount: string;
    /**
     * If absent assumes AUD
     */
    paymentCurrency?: string;
    /**
     * Date that the next payment for the card is due
     */
    paymentDueDate: string;
}