/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { DomesticPayeeAccount } from './domesticPayeeAccount';
import { DomesticPayeeCard } from './domesticPayeeCard';
import { DomesticPayeePayId } from './domesticPayeePayId';


export interface DomesticPayee { 
    /**
     * Type of account object included. Valid values are: { payeeAccountUType - - account A standard Australian account defined by BSB/Account Number payId A PayID recognised by NPP
     */
    payeeAccountUType: DomesticPayee.PayeeAccountUTypeEnum;
    account?: DomesticPayeeAccount;
    card?: DomesticPayeeCard;
    payId?: DomesticPayeePayId;
}
export namespace DomesticPayee {
    export type PayeeAccountUTypeEnum = 'account' | 'card' | 'payId';
    export const PayeeAccountUTypeEnum = {
        Account: 'account' as PayeeAccountUTypeEnum,
        Card: 'card' as PayeeAccountUTypeEnum,
        PayId: 'payId' as PayeeAccountUTypeEnum
    };
}