/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PhoneNumber { 
    /**
     * Required to be true for one and only one entry to indicate the preferred phone number.  Assumed to be 'false' if not present
     */
    isPreferred?: boolean;
    /**
     * The purpose of the number as specified by the customer
     */
    purpose: PhoneNumber.PurposeEnum;
    /**
     * If absent, assumed to be Australia (+61). The + should be included
     */
    countryCode?: string;
    /**
     * Required for non Mobile Phones, if field is present and refers to Australian code - the leading 0 should be omitted.
     */
    areaCode?: string;
    /**
     * The actual phone number, with leading zeros as appropriate
     */
    number: string;
    /**
     * An extension number (if applicable)
     */
    extension?: string;
    /**
     * Fully formatted phone number with country code, area code, number and extension incorporated. Formatted according to section 5.1.4. of RFC 3966
     */
    fullNumber: string;
}
export namespace PhoneNumber {
    export type PurposeEnum = 'MOBILE' | 'HOME' | 'WORK' | 'OTHER' | 'INTERNATIONAL' | 'UNSPECIFIED';
    export const PurposeEnum = {
        MOBILE: 'MOBILE' as PurposeEnum,
        HOME: 'HOME' as PurposeEnum,
        WORK: 'WORK' as PurposeEnum,
        OTHER: 'OTHER' as PurposeEnum,
        INTERNATIONAL: 'INTERNATIONAL' as PurposeEnum,
        UNSPECIFIED: 'UNSPECIFIED' as PurposeEnum
    };
}