/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ProductConstraints { 
    /**
     * The type of constraint described.  See the next section for an overview of valid values and their meaning
     */
    constraintType: ProductConstraints.ConstraintTypeEnum;
    /**
     * Generic field containing additional information relevant to the constraintType specified.  Whether mandatory or not is dependent on the value of constraintType
     */
    additionalValue?: string;
}
export namespace ProductConstraints {
    export type ConstraintTypeEnum = 'MIN_BALANCE' | 'OPENING_BALANCE' | 'MAX_LIMIT' | 'MIN_LIMIT';
    export const ConstraintTypeEnum = {
        MINBALANCE: 'MIN_BALANCE' as ConstraintTypeEnum,
        OPENINGBALANCE: 'OPENING_BALANCE' as ConstraintTypeEnum,
        MAXLIMIT: 'MAX_LIMIT' as ConstraintTypeEnum,
        MINLIMIT: 'MIN_LIMIT' as ConstraintTypeEnum
    };
}