/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Organisation } from './organisation';
import { Person } from './person';


export interface ResponseCommonCustomerData { 
    /**
     * The type of customer object that is present
     */
    customerUType?: ResponseCommonCustomerData.CustomerUTypeEnum;
    person?: Person;
    organisation?: Organisation;
}
export namespace ResponseCommonCustomerData {
    export type CustomerUTypeEnum = 'person' | 'organisation';
    export const CustomerUTypeEnum = {
        Person: 'person' as CustomerUTypeEnum,
        Organisation: 'organisation' as CustomerUTypeEnum
    };
}