/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ConsumerDataStandards);
  }
}(this, function(expect, ConsumerDataStandards) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ConsumerDataStandards.LoanAccount();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoanAccount', function() {
    it('should create an instance of LoanAccount', function() {
      // uncomment below and update the code to test LoanAccount
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be.a(ConsumerDataStandards.LoanAccount);
    });

    it('should have the property originalStartDate (base name: "originalStartDate")', function() {
      // uncomment below and update the code to test the property originalStartDate
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property originalLoanAmount (base name: "originalLoanAmount")', function() {
      // uncomment below and update the code to test the property originalLoanAmount
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property originalLoanCurrency (base name: "originalLoanCurrency")', function() {
      // uncomment below and update the code to test the property originalLoanCurrency
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property loanEndDate (base name: "loanEndDate")', function() {
      // uncomment below and update the code to test the property loanEndDate
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property nextInstalmentDate (base name: "nextInstalmentDate")', function() {
      // uncomment below and update the code to test the property nextInstalmentDate
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property minInstalmentAmount (base name: "minInstalmentAmount")', function() {
      // uncomment below and update the code to test the property minInstalmentAmount
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property minInstalmentCurrency (base name: "minInstalmentCurrency")', function() {
      // uncomment below and update the code to test the property minInstalmentCurrency
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property maxRedraw (base name: "maxRedraw")', function() {
      // uncomment below and update the code to test the property maxRedraw
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property maxRedrawCurrency (base name: "maxRedrawCurrency")', function() {
      // uncomment below and update the code to test the property maxRedrawCurrency
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property minRedraw (base name: "minRedraw")', function() {
      // uncomment below and update the code to test the property minRedraw
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property minRedrawCurrency (base name: "minRedrawCurrency")', function() {
      // uncomment below and update the code to test the property minRedrawCurrency
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property offsetAccountEnabled (base name: "offsetAccountEnabled")', function() {
      // uncomment below and update the code to test the property offsetAccountEnabled
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property offsetAccountIds (base name: "offsetAccountIds")', function() {
      // uncomment below and update the code to test the property offsetAccountIds
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property repaymentFrequency (base name: "repaymentFrequency")', function() {
      // uncomment below and update the code to test the property repaymentFrequency
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

    it('should have the property repaymentType (base name: "repaymentType")', function() {
      // uncomment below and update the code to test the property repaymentType
      //var instance = new ConsumerDataStandards.LoanAccount();
      //expect(instance).to.be();
    });

  });

}));
