/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ConsumerDataStandards);
  }
}(this, function(expect, ConsumerDataStandards) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ConsumerDataStandards.TransactionDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionDetail', function() {
    it('should create an instance of TransactionDetail', function() {
      // uncomment below and update the code to test TransactionDetail
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be.a(ConsumerDataStandards.TransactionDetail);
    });

    it('should have the property accountId (base name: "accountId")', function() {
      // uncomment below and update the code to test the property accountId
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionId (base name: "transactionId")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property isDetailAvailable (base name: "isDetailAvailable")', function() {
      // uncomment below and update the code to test the property isDetailAvailable
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property postingDateTime (base name: "postingDateTime")', function() {
      // uncomment below and update the code to test the property postingDateTime
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property valueDateTime (base name: "valueDateTime")', function() {
      // uncomment below and update the code to test the property valueDateTime
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property executionDateTime (base name: "executionDateTime")', function() {
      // uncomment below and update the code to test the property executionDateTime
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property merchantName (base name: "merchantName")', function() {
      // uncomment below and update the code to test the property merchantName
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property merchantCategoryCode (base name: "merchantCategoryCode")', function() {
      // uncomment below and update the code to test the property merchantCategoryCode
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property billerCode (base name: "billerCode")', function() {
      // uncomment below and update the code to test the property billerCode
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property billerName (base name: "billerName")', function() {
      // uncomment below and update the code to test the property billerName
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property crn (base name: "crn")', function() {
      // uncomment below and update the code to test the property crn
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property apcaNumber (base name: "apcaNumber")', function() {
      // uncomment below and update the code to test the property apcaNumber
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

    it('should have the property extendedData (base name: "extendedData")', function() {
      // uncomment below and update the code to test the property extendedData
      //var instance = new ConsumerDataStandards.TransactionDetail();
      //expect(instance).to.be();
    });

  });

}));
