/**
* Consumer Data Standards
* API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
*
* OpenAPI spec version: 1-oas3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.PAFAddress
import org.openapitools.server.models.PhysicalAddress
import org.openapitools.server.models.SimpleAddress

/**
 * 
 * @param addressUType The type of address object present
 * @param simple 
 * @param paf 
 * @param purpose Enumeration of values indicating the purpose of the physical address
 */
data class PhysicalAddressWithPurpose (
    /* The type of address object present */
    val addressUType: PhysicalAddressWithPurpose.AddressUType,
    /* Enumeration of values indicating the purpose of the physical address */
    val purpose: PhysicalAddressWithPurpose.Purpose,
    val simple: SimpleAddress? = null,
    val paf: PAFAddress? = null
) {

    /**
    * The type of address object present
    * Values: simple,paf
    */
    enum class AddressUType(val value: kotlin.String){
    
        simple("simple"),
    
        paf("paf");
    
    }

    /**
    * Enumeration of values indicating the purpose of the physical address
    * Values: rEGISTERED,mAIL,pHYSICAL,wORK,oTHER
    */
    enum class Purpose(val value: kotlin.String){
    
        rEGISTERED("REGISTERED"),
    
        mAIL("MAIL"),
    
        pHYSICAL("PHYSICAL"),
    
        wORK("WORK"),
    
        oTHER("OTHER");
    
    }

}

