/**
* Consumer Data Standards
* API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
*
* OpenAPI spec version: 1-oas3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param overviewUri General overview of the product
 * @param termsUri Terms and conditions for the product
 * @param eligibilityUri Eligibility rules and criteria for the product
 * @param feesAndPricingUri Description of fees, pricing, discounts, exemptions and bonuses for the product
 * @param bundleUri Description of a bundle that this product can be part of
 */
data class ProductAdditionalInformation (
    /* General overview of the product */
    val overviewUri: kotlin.String? = null,
    /* Terms and conditions for the product */
    val termsUri: kotlin.String? = null,
    /* Eligibility rules and criteria for the product */
    val eligibilityUri: kotlin.String? = null,
    /* Description of fees, pricing, discounts, exemptions and bonuses for the product */
    val feesAndPricingUri: kotlin.String? = null,
    /* Description of a bundle that this product can be part of */
    val bundleUri: kotlin.String? = null
) {

}

