//
// DepositBalance.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct DepositBalance: Codable {


    public var currentBalance: CurrencyAmount

    public var availableBalance: CurrencyAmount
    public init(currentBalance: CurrencyAmount, availableBalance: CurrencyAmount) { 
        self.currentBalance = currentBalance
        self.availableBalance = availableBalance
    }

}
