//
// LinksPaginated.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct LinksPaginated: Codable {


    /** Fully qualified link to this API call */
    public var _self: String?

    /** URI to the first page of this set. Mandatory if this response is not the first page */
    public var first: String?

    /** URI to the first previous page of this set. Mandatory if this response is not the first page */
    public var prev: String?

    /** URI to the first next page of this set. Mandatory if this response is not the last page */
    public var next: String?

    /** URI to the first last page of this set. Mandatory if this response is not the last page */
    public var last: String?
    public init(_self: String?, first: String?, prev: String?, next: String?, last: String?) { 
        self._self = _self
        self.first = first
        self.prev = prev
        self.next = next
        self.last = last
    }
    public enum CodingKeys: String, CodingKey { 
        case _self = "self"
        case first
        case prev
        case next
        case last
    }

}
