//
// ProductConstraints.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ProductConstraints: Codable {

    public enum ConstraintType: String, Codable { 
        case minBalance = "MIN_BALANCE"
        case openingBalance = "OPENING_BALANCE"
        case maxLimit = "MAX_LIMIT"
        case minLimit = "MIN_LIMIT"
    }    /** The type of constraint described.  See the next section for an overview of valid values and their meaning */
    public var constraintType: ConstraintType

    /** Generic field containing additional information relevant to the constraintType specified.  Whether mandatory or not is dependent on the value of constraintType */
    public var additionalValue: String?
    public init(constraintType: ConstraintType, additionalValue: String?) { 
        self.constraintType = constraintType
        self.additionalValue = additionalValue
    }

}
