//
// ProductEligibility.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ProductEligibility: Codable {

    public enum EligibilityType: String, Codable { 
        case business = "BUSINESS"
        case pensionRecipient = "PENSION_RECIPIENT"
        case minAge = "MIN_AGE"
        case maxAge = "MAX_AGE"
        case minIncome = "MIN_INCOME"
        case minTurnover = "MIN_TURNOVER"
        case staff = "STAFF"
        case student = "STUDENT"
        case employmentStatus = "EMPLOYMENT_STATUS"
        case residencyStatus = "RESIDENCY_STATUS"
        case other = "OTHER"
    }    /** The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning */
    public var eligibilityType: EligibilityType

    /** Generic field containing additional information relevant to the eligibilityType specified.  Whether mandatory or not is dependent on the value of eligibilityType */
    public var additionalValue: String?

    /** Display text providing more information on the eligibility criteria. Mandatory if the eligibilityType field is set to OTHER */
    public var additionalInfo: String?

    /** Link to a web page with more information on this eligibility criteria */
    public var additionalInfoUri: String?
    public init(eligibilityType: EligibilityType, additionalValue: String?, additionalInfo: String?, additionalInfoUri: String?) { 
        self.eligibilityType = eligibilityType
        self.additionalValue = additionalValue
        self.additionalInfo = additionalInfo
        self.additionalInfoUri = additionalInfoUri
    }

}
