//
// ResponseBankingPayeeDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ResponseBankingPayeeDetails: Codable {


    public var data: PayeeDetail

    public var links: Links

    public var meta: Meta
    public init(data: PayeeDetail, links: Links, meta: Meta) { 
        self.data = data
        self.links = links
        self.meta = meta
    }

}
