//
// ResponseBankingTransactionDetailData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ResponseBankingTransactionDetailData: Codable {


    /** ID of the account for which transactions are provided */
    public var accountId: String?

    /** The display name of the account as defined by the bank.  This should not incorporate account numbers or PANs.  If it does the values should be masked according to the rules of the MaskedAccountString common type. */
    public var displayName: String?

    /** A customer supplied nick name for the account */
    public var nickname: String?

    public var transaction: [TransactionDetail]?
    public init(accountId: String?, displayName: String?, nickname: String?, transaction: [TransactionDetail]?) { 
        self.accountId = accountId
        self.displayName = displayName
        self.nickname = nickname
        self.transaction = transaction
    }

}
