//
// ResponseBankingProduct.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ResponseBankingProduct: Codable {


    public var data: ProductDetail

    public var links: Links

    public var meta: Meta
    public init(data: ProductDetail, links: Links, meta: Meta) { 
        self.data = data
        self.links = links
        self.meta = meta
    }

}
