/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbank.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * CreditCardAccount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-17T21:56:09.632+11:00[Australia/Sydney]")
public class CreditCardAccount {
  public static final String SERIALIZED_NAME_MIN_PAYMENT_AMOUNT = "minPaymentAmount";
  @SerializedName(SERIALIZED_NAME_MIN_PAYMENT_AMOUNT)
  private String minPaymentAmount;

  public static final String SERIALIZED_NAME_PAYMENT_DUE_AMOUNT = "paymentDueAmount";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DUE_AMOUNT)
  private String paymentDueAmount;

  public static final String SERIALIZED_NAME_PAYMENT_CURRENCY = "paymentCurrency";
  @SerializedName(SERIALIZED_NAME_PAYMENT_CURRENCY)
  private String paymentCurrency;

  public static final String SERIALIZED_NAME_PAYMENT_DUE_DATE = "paymentDueDate";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DUE_DATE)
  private String paymentDueDate;

  public CreditCardAccount minPaymentAmount(String minPaymentAmount) {
    this.minPaymentAmount = minPaymentAmount;
    return this;
  }

   /**
   * The minimum payment amount due for the next card payment
   * @return minPaymentAmount
  **/
  @ApiModelProperty(required = true, value = "The minimum payment amount due for the next card payment")
  public String getMinPaymentAmount() {
    return minPaymentAmount;
  }

  public void setMinPaymentAmount(String minPaymentAmount) {
    this.minPaymentAmount = minPaymentAmount;
  }

  public CreditCardAccount paymentDueAmount(String paymentDueAmount) {
    this.paymentDueAmount = paymentDueAmount;
    return this;
  }

   /**
   * The amount due for the next card payment
   * @return paymentDueAmount
  **/
  @ApiModelProperty(required = true, value = "The amount due for the next card payment")
  public String getPaymentDueAmount() {
    return paymentDueAmount;
  }

  public void setPaymentDueAmount(String paymentDueAmount) {
    this.paymentDueAmount = paymentDueAmount;
  }

  public CreditCardAccount paymentCurrency(String paymentCurrency) {
    this.paymentCurrency = paymentCurrency;
    return this;
  }

   /**
   * If absent assumes AUD
   * @return paymentCurrency
  **/
  @ApiModelProperty(value = "If absent assumes AUD")
  public String getPaymentCurrency() {
    return paymentCurrency;
  }

  public void setPaymentCurrency(String paymentCurrency) {
    this.paymentCurrency = paymentCurrency;
  }

  public CreditCardAccount paymentDueDate(String paymentDueDate) {
    this.paymentDueDate = paymentDueDate;
    return this;
  }

   /**
   * Date that the next payment for the card is due
   * @return paymentDueDate
  **/
  @ApiModelProperty(required = true, value = "Date that the next payment for the card is due")
  public String getPaymentDueDate() {
    return paymentDueDate;
  }

  public void setPaymentDueDate(String paymentDueDate) {
    this.paymentDueDate = paymentDueDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditCardAccount creditCardAccount = (CreditCardAccount) o;
    return Objects.equals(this.minPaymentAmount, creditCardAccount.minPaymentAmount) &&
        Objects.equals(this.paymentDueAmount, creditCardAccount.paymentDueAmount) &&
        Objects.equals(this.paymentCurrency, creditCardAccount.paymentCurrency) &&
        Objects.equals(this.paymentDueDate, creditCardAccount.paymentDueDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minPaymentAmount, paymentDueAmount, paymentCurrency, paymentDueDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditCardAccount {\n");
    sb.append("    minPaymentAmount: ").append(toIndentedString(minPaymentAmount)).append("\n");
    sb.append("    paymentDueAmount: ").append(toIndentedString(paymentDueAmount)).append("\n");
    sb.append("    paymentCurrency: ").append(toIndentedString(paymentCurrency)).append("\n");
    sb.append("    paymentDueDate: ").append(toIndentedString(paymentDueDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

