/**
* Consumer Data Standards
* API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
*
* OpenAPI spec version: 1-oas3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.InternationalPayeeBankDetailsBankAddress

/**
 * 
 * @param country Country of the recipient institution. A valid ISO 3166 Alpha-3 country code
 * @param accountNumber Account Targeted for payment
 * @param bankAddress 
 * @param beneficiaryBankBIC Swift bank code.  Aligns with standard [ISO 9362](https://www.iso.org/standard/60390.html)
 * @param fedWireNumber Number for Fedwire payment (Federal Reserve Wire Network)
 * @param sortCode Sort code used for account identification in some jurisdictions
 * @param chipNumber Number for the Clearing House Interbank Payments System
 * @param routingNumber International bank routing number
 * @param legalEntityIdentifier The legal entity identifier (LEI) for the beneficiary.  Aligns with [ISO 17442](https://www.iso.org/standard/59771.html)
 */
data class InternationalPayeeBankDetails (

    /* Country of the recipient institution. A valid ISO 3166 Alpha-3 country code */
    val country: kotlin.String? = null,
    /* Account Targeted for payment */
    val accountNumber: kotlin.String? = null,
    val bankAddress: InternationalPayeeBankDetailsBankAddress? = null,
    /* Swift bank code.  Aligns with standard [ISO 9362](https://www.iso.org/standard/60390.html) */
    val beneficiaryBankBIC: kotlin.String? = null,
    /* Number for Fedwire payment (Federal Reserve Wire Network) */
    val fedWireNumber: kotlin.String? = null,
    /* Sort code used for account identification in some jurisdictions */
    val sortCode: kotlin.String? = null,
    /* Number for the Clearing House Interbank Payments System */
    val chipNumber: kotlin.String? = null,
    /* International bank routing number */
    val routingNumber: kotlin.String? = null,
    /* The legal entity identifier (LEI) for the beneficiary.  Aligns with [ISO 17442](https://www.iso.org/standard/59771.html) */
    val legalEntityIdentifier: kotlin.String? = null
) {
}