/**
* Consumer Data Standards
* API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
*
* OpenAPI spec version: 1-oas3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param payer Name or description of the originating payer.  Mandatory for inbound payment
 * @param payee Name or description of the target payee. Mandatory for an outbound payment
 * @param extensionUType Optional extended data provided specific to transaction originated via NPP
 * @param extendedDescription An extended string description. Only present if specified by the extensionUType field
 * @param serviceId Identifier of the applicable NPP payment service
 */
data class TransactionDetailExtendedData (

    /* Name or description of the originating payer.  Mandatory for inbound payment */
    val payer: kotlin.String? = null,
    /* Name or description of the target payee. Mandatory for an outbound payment */
    val payee: kotlin.String? = null,
    /* Optional extended data provided specific to transaction originated via NPP */
    val extensionUType: TransactionDetailExtendedData.ExtensionUType? = null,
    /* An extended string description. Only present if specified by the extensionUType field */
    val extendedDescription: kotlin.String? = null,
    /* Identifier of the applicable NPP payment service */
    val serviceId: TransactionDetailExtendedData.ServiceId? = null
) {
    /**
    * Optional extended data provided specific to transaction originated via NPP
    * Values: extendedDescription
    */
    enum class ExtensionUType(val value: kotlin.String){
        extendedDescription("extendedDescription");
    }
    /**
    * Identifier of the applicable NPP payment service
    * Values: 01
    */
    enum class ServiceId(val value: kotlin.String){
        01("X2P1.01");
    }
}