<?php
/**
 * EnumProductCategory
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* Consumer Data Standards
 *
* API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
* OpenAPI spec version: 1-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * EnumProductCategory Class Doc Comment
 *
 * @category Class
 * @description The list of available product categories for categorising products and accounts
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EnumProductCategory
{
    /**
     * Possible values of this enum
     */
    const PERS_AT_CALL_DEPOSITS = 'PERS_AT_CALL_DEPOSITS';
const BUS_AT_CALL_DEPOSITS = 'BUS_AT_CALL_DEPOSITS';
const TERM_DEPOSITS = 'TERM_DEPOSITS';
const RESIDENTIAL_MORTGAGES = 'RESIDENTIAL_MORTGAGES';
const PERS_CRED_AND_CHRG_CARDS = 'PERS_CRED_AND_CHRG_CARDS';
const BUS_CRED_AND_CHRG_CARDS = 'BUS_CRED_AND_CHRG_CARDS';
const PERS_LOANS = 'PERS_LOANS';
const PERS_LEASING = 'PERS_LEASING';
const BUS_LEASING = 'BUS_LEASING';
const TRADE_FINANCE = 'TRADE_FINANCE';
const PERS_OVERDRAFT = 'PERS_OVERDRAFT';
const BUS_OVERDRAFT = 'BUS_OVERDRAFT';
const BUS_LOANS = 'BUS_LOANS';
const FOREIGN_CURR_AT_CALL_DEPOSITS = 'FOREIGN_CURR_AT_CALL_DEPOSITS';
const FOREIGN_CURR_TERM_DEPOSITS = 'FOREIGN_CURR_TERM_DEPOSITS';
const FOREIGN_CURR_LOAN = 'FOREIGN_CURR_LOAN';
const FOREIGN_CURRRENCT_OVERDRAFT = 'FOREIGN_CURRRENCT_OVERDRAFT';
const TRAVEL_CARD = 'TRAVEL_CARD';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PERS_AT_CALL_DEPOSITS,
self::BUS_AT_CALL_DEPOSITS,
self::TERM_DEPOSITS,
self::RESIDENTIAL_MORTGAGES,
self::PERS_CRED_AND_CHRG_CARDS,
self::BUS_CRED_AND_CHRG_CARDS,
self::PERS_LOANS,
self::PERS_LEASING,
self::BUS_LEASING,
self::TRADE_FINANCE,
self::PERS_OVERDRAFT,
self::BUS_OVERDRAFT,
self::BUS_LOANS,
self::FOREIGN_CURR_AT_CALL_DEPOSITS,
self::FOREIGN_CURR_TERM_DEPOSITS,
self::FOREIGN_CURR_LOAN,
self::FOREIGN_CURRRENCT_OVERDRAFT,
self::TRAVEL_CARD,        ];
    }
}
