/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorList;
import io.swagger.client.model.RequestAccountIds;
import io.swagger.client.model.ResponseBankingDirectDebits;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DirectDebitsApi
 */
@Ignore
public class DirectDebitsApiTest {

    private final DirectDebitsApi api = new DirectDebitsApi();

    /**
     * Get Direct Debits For Account
     *
     * Obtain direct debit authorisations for a specific account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDirectDebitsTest() throws ApiException {
        String accountId = null;
        Integer page = null;
        Integer pageSize = null;
        ResponseBankingDirectDebits response = api.listDirectDebits(accountId, page, pageSize);

        // TODO: test validations
    }
    /**
     * Get Bulk Direct Debits
     *
     * Obtain direct debit authorisations for multiple, filtered accounts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDirectDebitsBulkTest() throws ApiException {
        String isOwned = null;
        String productCategory = null;
        Integer page = null;
        Integer pageSize = null;
        ResponseBankingDirectDebits response = api.listDirectDebitsBulk(isOwned, productCategory, page, pageSize);

        // TODO: test validations
    }
    /**
     * Get Direct Debits For Specific Accounts
     *
     * Obtain direct debit authorisations for a specified list of accounts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDirectDebitsSpecificAccountsTest() throws ApiException {
        RequestAccountIds body = null;
        ResponseBankingDirectDebits response = api.listDirectDebitsSpecificAccounts(body);

        // TODO: test validations
    }
}
