/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


/**
 * @param amount The current balance of the account at this time. Should align to the current balance available via other channels such as ATM balance enquiry or Internet Banking
 * @param currency If not present assumes AUD
 */
case class CurrencyAmount (
  amount: String,
  currency: Option[String]
)

