/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


/**
 * @param payeeAccountUType Type of account object included. Valid values are: { payeeAccountUType - - account A standard Australian account defined by BSB/Account Number payId A PayID recognised by NPP
 * @param account 
 * @param card 
 * @param payId 
 */
case class DomesticPayee (
  payeeAccountUType: String,
  account: Option[DomesticPayeeAccount],
  card: Option[DomesticPayeeCard],
  payId: Option[DomesticPayeePayId]
)

