<?php
/**
 * ProductAdditionalInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* Consumer Data Standards
 *
* API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
* OpenAPI spec version: 1-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductAdditionalInformationTest Class Doc Comment
 *
 * @category    Class
 * @description ProductAdditionalInformation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductAdditionalInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductAdditionalInformation"
     */
    public function testProductAdditionalInformation()
    {
    }

    /**
     * Test attribute "overview_uri"
     */
    public function testPropertyOverviewUri()
    {
    }

    /**
     * Test attribute "terms_uri"
     */
    public function testPropertyTermsUri()
    {
    }

    /**
     * Test attribute "eligibility_uri"
     */
    public function testPropertyEligibilityUri()
    {
    }

    /**
     * Test attribute "fees_and_pricing_uri"
     */
    public function testPropertyFeesAndPricingUri()
    {
    }

    /**
     * Test attribute "bundle_uri"
     */
    public function testPropertyBundleUri()
    {
    }
}
