/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbanking.client.model;

import org.openbanking.client.model.*;
import org.junit.Test;


/**
 * Model tests for AccountDetail
 */
public class AccountDetailTest {
    private final AccountDetail model = new AccountDetail();

    /**
     * Model tests for AccountDetail
     */
    @Test
    public void testAccountDetail() {
        // TODO: test AccountDetail
    }

    /**
     * Test the property 'bsb'
     */
    @Test
    public void bsbTest() {
        // TODO: test bsb
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'bundleName'
     */
    @Test
    public void bundleNameTest() {
        // TODO: test bundleName
    }

    /**
     * Test the property 'specificAccountUType'
     */
    @Test
    public void specificAccountUTypeTest() {
        // TODO: test specificAccountUType
    }

    /**
     * Test the property 'termDeposit'
     */
    @Test
    public void termDepositTest() {
        // TODO: test termDeposit
    }

    /**
     * Test the property 'creditCard'
     */
    @Test
    public void creditCardTest() {
        // TODO: test creditCard
    }

    /**
     * Test the property 'loan'
     */
    @Test
    public void loanTest() {
        // TODO: test loan
    }

    /**
     * Test the property 'features'
     */
    @Test
    public void featuresTest() {
        // TODO: test features
    }

    /**
     * Test the property 'fees'
     */
    @Test
    public void feesTest() {
        // TODO: test fees
    }

    /**
     * Test the property 'depositRates'
     */
    @Test
    public void depositRatesTest() {
        // TODO: test depositRates
    }

    /**
     * Test the property 'lendingRates'
     */
    @Test
    public void lendingRatesTest() {
        // TODO: test lendingRates
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

}
