/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbank.client.model;

import org.openbank.client.model.Account;
import org.junit.Test;


/**
 * Model tests for Account
 */
public class AccountTest {
    private final Account model = new Account();

    /**
     * Model tests for Account
     */
    @Test
    public void testAccount() {
        // TODO: test Account
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'nickname'
     */
    @Test
    public void nicknameTest() {
        // TODO: test nickname
    }

    /**
     * Test the property 'maskedNumber'
     */
    @Test
    public void maskedNumberTest() {
        // TODO: test maskedNumber
    }

    /**
     * Test the property 'openStatus'
     */
    @Test
    public void openStatusTest() {
        // TODO: test openStatus
    }

    /**
     * Test the property 'isOwned'
     */
    @Test
    public void isOwnedTest() {
        // TODO: test isOwned
    }

    /**
     * Test the property 'productCategory'
     */
    @Test
    public void productCategoryTest() {
        // TODO: test productCategory
    }

    /**
     * Test the property 'productName'
     */
    @Test
    public void productNameTest() {
        // TODO: test productName
    }

}
