/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbank.client.model;

import org.junit.Test;
import org.openbank.client.model.AuthorisedEntity;


/**
 * Model tests for AuthorisedEntity
 */
public class AuthorisedEntityTest {
    private final AuthorisedEntity model = new AuthorisedEntity();

    /**
     * Model tests for AuthorisedEntity
     */
    @Test
    public void testAuthorisedEntity() {
        // TODO: test AuthorisedEntity
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'financialInstitution'
     */
    @Test
    public void financialInstitutionTest() {
        // TODO: test financialInstitution
    }

    /**
     * Test the property 'abn'
     */
    @Test
    public void abnTest() {
        // TODO: test abn
    }

    /**
     * Test the property 'acn'
     */
    @Test
    public void acnTest() {
        // TODO: test acn
    }

    /**
     * Test the property 'arbn'
     */
    @Test
    public void arbnTest() {
        // TODO: test arbn
    }

}
