/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbank.client.model;

import org.openbank.client.model.Balance;
import org.junit.Test;


/**
 * Model tests for Balance
 */
public class BalanceTest {
    private final Balance model = new Balance();

    /**
     * Model tests for Balance
     */
    @Test
    public void testBalance() {
        // TODO: test Balance
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'balanceUType'
     */
    @Test
    public void balanceUTypeTest() {
        // TODO: test balanceUType
    }

    /**
     * Test the property 'deposit'
     */
    @Test
    public void depositTest() {
        // TODO: test deposit
    }

    /**
     * Test the property 'lending'
     */
    @Test
    public void lendingTest() {
        // TODO: test lending
    }

    /**
     * Test the property 'purses'
     */
    @Test
    public void pursesTest() {
        // TODO: test purses
    }

}
