/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbank.client.model;

import org.junit.Test;
import org.openbank.client.model.CreditCardAccount;


/**
 * Model tests for CreditCardAccount
 */
public class CreditCardAccountTest {
    private final CreditCardAccount model = new CreditCardAccount();

    /**
     * Model tests for CreditCardAccount
     */
    @Test
    public void testCreditCardAccount() {
        // TODO: test CreditCardAccount
    }

    /**
     * Test the property 'minPaymentAmount'
     */
    @Test
    public void minPaymentAmountTest() {
        // TODO: test minPaymentAmount
    }

    /**
     * Test the property 'paymentDueAmount'
     */
    @Test
    public void paymentDueAmountTest() {
        // TODO: test paymentDueAmount
    }

    /**
     * Test the property 'paymentCurrency'
     */
    @Test
    public void paymentCurrencyTest() {
        // TODO: test paymentCurrency
    }

    /**
     * Test the property 'paymentDueDate'
     */
    @Test
    public void paymentDueDateTest() {
        // TODO: test paymentDueDate
    }

}
