/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbanking.client.model;

import org.junit.Test;
import org.openbanking.client.model.DepositBalance;


/**
 * Model tests for DepositBalance
 */
public class DepositBalanceTest {
    private final DepositBalance model = new DepositBalance();

    /**
     * Model tests for DepositBalance
     */
    @Test
    public void testDepositBalance() {
        // TODO: test DepositBalance
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

}
