/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbanking.client.model;

import org.junit.Test;
import org.openbanking.client.model.EmailAddress;


/**
 * Model tests for EmailAddress
 */
public class EmailAddressTest {
    private final EmailAddress model = new EmailAddress();

    /**
     * Model tests for EmailAddress
     */
    @Test
    public void testEmailAddress() {
        // TODO: test EmailAddress
    }

    /**
     * Test the property 'isPreferred'
     */
    @Test
    public void isPreferredTest() {
        // TODO: test isPreferred
    }

    /**
     * Test the property 'purpose'
     */
    @Test
    public void purposeTest() {
        // TODO: test purpose
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

}
