/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbanking.client.model;

import org.junit.Test;
import org.openbanking.client.model.InternationalPayeeBeneficiaryDetails;


/**
 * Model tests for InternationalPayeeBeneficiaryDetails
 */
public class InternationalPayeeBeneficiaryDetailsTest {
    private final InternationalPayeeBeneficiaryDetails model = new InternationalPayeeBeneficiaryDetails();

    /**
     * Model tests for InternationalPayeeBeneficiaryDetails
     */
    @Test
    public void testInternationalPayeeBeneficiaryDetails() {
        // TODO: test InternationalPayeeBeneficiaryDetails
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
