/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbank.client.model;

import org.junit.Test;
import org.openbank.client.model.LendingBalance;


/**
 * Model tests for LendingBalance
 */
public class LendingBalanceTest {
    private final LendingBalance model = new LendingBalance();

    /**
     * Model tests for LendingBalance
     */
    @Test
    public void testLendingBalance() {
        // TODO: test LendingBalance
    }

    /**
     * Test the property 'accountBalance'
     */
    @Test
    public void accountBalanceTest() {
        // TODO: test accountBalance
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'creditLimit'
     */
    @Test
    public void creditLimitTest() {
        // TODO: test creditLimit
    }

    /**
     * Test the property 'amortisedLimit'
     */
    @Test
    public void amortisedLimitTest() {
        // TODO: test amortisedLimit
    }

}
