/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbank.client.model;

import org.openbank.client.model.ResponseBankingTransactionDetailData;
import org.junit.Test;


/**
 * Model tests for ResponseBankingTransactionDetailData
 */
public class ResponseBankingTransactionDetailDataTest {
    private final ResponseBankingTransactionDetailData model = new ResponseBankingTransactionDetailData();

    /**
     * Model tests for ResponseBankingTransactionDetailData
     */
    @Test
    public void testResponseBankingTransactionDetailData() {
        // TODO: test ResponseBankingTransactionDetailData
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'nickname'
     */
    @Test
    public void nicknameTest() {
        // TODO: test nickname
    }

    /**
     * Test the property 'transaction'
     */
    @Test
    public void transactionTest() {
        // TODO: test transaction
    }

}
