/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Transaction;
import io.swagger.client.model.TransactionDetailExtendedData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * TransactionDetail
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-14T03:38:22.905Z[GMT]")public class TransactionDetail extends Transaction {

  @SerializedName("extendedData")
  private TransactionDetailExtendedData extendedData = null;
  public TransactionDetail extendedData(TransactionDetailExtendedData extendedData) {
    this.extendedData = extendedData;
    return this;
  }

  

  /**
  * Get extendedData
  * @return extendedData
  **/
  @Schema(required = true, description = "")
  public TransactionDetailExtendedData getExtendedData() {
    return extendedData;
  }
  public void setExtendedData(TransactionDetailExtendedData extendedData) {
    this.extendedData = extendedData;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionDetail transactionDetail = (TransactionDetail) o;
    return Objects.equals(this.extendedData, transactionDetail.extendedData) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(extendedData, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionDetail {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    extendedData: ").append(toIndentedString(extendedData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
