/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ConsumerDataStandards) {
      root.ConsumerDataStandards = {};
    }
    root.ConsumerDataStandards.DomesticPayeePayId = factory(root.ConsumerDataStandards.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The DomesticPayeePayId model module.
   * @module model/DomesticPayeePayId
   * @version 1-oas3
   */

  /**
   * Constructs a new <code>DomesticPayeePayId</code>.
   * @alias module:model/DomesticPayeePayId
   * @class
   * @param identifier {String} The identifier of the PayID (dependent on type)
   * @param type {module:model/DomesticPayeePayId.TypeEnum} The type of the PayID
   */
  var exports = function(identifier, type) {
    var _this = this;

    _this['identifier'] = identifier;
    _this['type'] = type;
  };

  /**
   * Constructs a <code>DomesticPayeePayId</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DomesticPayeePayId} obj Optional instance to populate.
   * @return {module:model/DomesticPayeePayId} The populated <code>DomesticPayeePayId</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('identifier')) {
        obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * The name assigned to the PayID by the owner of the PayID
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The identifier of the PayID (dependent on type)
   * @member {String} identifier
   */
  exports.prototype['identifier'] = undefined;
  /**
   * The type of the PayID
   * @member {module:model/DomesticPayeePayId.TypeEnum} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "EMAIL"
     * @const
     */
    "EMAIL": "EMAIL",
    /**
     * value: "MOBILE"
     * @const
     */
    "MOBILE": "MOBILE",
    /**
     * value: "ORG_NUMBER"
     * @const
     */
    "ORG_NUMBER": "ORG_NUMBER",
    /**
     * value: "ORG_NAME"
     * @const
     */
    "ORG_NAME": "ORG_NAME"  };


  return exports;
}));


