/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ConsumerDataStandards) {
      root.ConsumerDataStandards = {};
    }
    root.ConsumerDataStandards.MetaPaginated = factory(root.ConsumerDataStandards.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The MetaPaginated model module.
   * @module model/MetaPaginated
   * @version 1-oas3
   */

  /**
   * Constructs a new <code>MetaPaginated</code>.
   * @alias module:model/MetaPaginated
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>MetaPaginated</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MetaPaginated} obj Optional instance to populate.
   * @return {module:model/MetaPaginated} The populated <code>MetaPaginated</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('totalRecords')) {
        obj['totalRecords'] = ApiClient.convertToType(data['totalRecords'], 'Number');
      }
      if (data.hasOwnProperty('totalPages')) {
        obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The total number of records in the full set
   * @member {Number} totalRecords
   */
  exports.prototype['totalRecords'] = undefined;
  /**
   * The total number of pages in the full set
   * @member {Number} totalPages
   */
  exports.prototype['totalPages'] = undefined;



  return exports;
}));


