/**
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ConsumerDataStandards) {
      root.ConsumerDataStandards = {};
    }
    root.ConsumerDataStandards.PAFAddress = factory(root.ConsumerDataStandards.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The PAFAddress model module.
   * @module model/PAFAddress
   * @version 1-oas3
   */

  /**
   * Constructs a new <code>PAFAddress</code>.
   * Australian address formatted according to the file format defined by the [PAF file format](https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-data-guide.pdf)
   * @alias module:model/PAFAddress
   * @class
   * @param localityName {String} Full name of locality
   * @param postcode {String} Postcode for the locality
   * @param state {String} State in which the address belongs. Valid enumeration defined by Australia Post PAF code file
   */
  var exports = function(localityName, postcode, state) {
    var _this = this;

    _this['localityName'] = localityName;
    _this['postcode'] = postcode;
    _this['state'] = state;
  };

  /**
   * Constructs a <code>PAFAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PAFAddress} obj Optional instance to populate.
   * @return {module:model/PAFAddress} The populated <code>PAFAddress</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('dpid')) {
        obj['dpid'] = ApiClient.convertToType(data['dpid'], 'String');
      }
      if (data.hasOwnProperty('thoroughfareNumber1')) {
        obj['thoroughfareNumber1'] = ApiClient.convertToType(data['thoroughfareNumber1'], 'Number');
      }
      if (data.hasOwnProperty('thoroughfareNumber1Suffix')) {
        obj['thoroughfareNumber1Suffix'] = ApiClient.convertToType(data['thoroughfareNumber1Suffix'], 'String');
      }
      if (data.hasOwnProperty('thoroughfareNumber2')) {
        obj['thoroughfareNumber2'] = ApiClient.convertToType(data['thoroughfareNumber2'], 'Number');
      }
      if (data.hasOwnProperty('thoroughfareNumber2Suffix')) {
        obj['thoroughfareNumber2Suffix'] = ApiClient.convertToType(data['thoroughfareNumber2Suffix'], 'String');
      }
      if (data.hasOwnProperty('flatUnitNumber')) {
        obj['flatUnitNumber'] = ApiClient.convertToType(data['flatUnitNumber'], 'String');
      }
      if (data.hasOwnProperty('floorLevelNumber')) {
        obj['floorLevelNumber'] = ApiClient.convertToType(data['floorLevelNumber'], 'String');
      }
      if (data.hasOwnProperty('lotNumber')) {
        obj['lotNumber'] = ApiClient.convertToType(data['lotNumber'], 'Number');
      }
      if (data.hasOwnProperty('buildingName1')) {
        obj['buildingName1'] = ApiClient.convertToType(data['buildingName1'], 'String');
      }
      if (data.hasOwnProperty('buildingName2')) {
        obj['buildingName2'] = ApiClient.convertToType(data['buildingName2'], 'String');
      }
      if (data.hasOwnProperty('streetName')) {
        obj['streetName'] = ApiClient.convertToType(data['streetName'], 'String');
      }
      if (data.hasOwnProperty('streetType')) {
        obj['streetType'] = ApiClient.convertToType(data['streetType'], 'String');
      }
      if (data.hasOwnProperty('streetSuffix')) {
        obj['streetSuffix'] = ApiClient.convertToType(data['streetSuffix'], 'String');
      }
      if (data.hasOwnProperty('postalDeliveryType')) {
        obj['postalDeliveryType'] = ApiClient.convertToType(data['postalDeliveryType'], 'String');
      }
      if (data.hasOwnProperty('postalDeliveryNumber')) {
        obj['postalDeliveryNumber'] = ApiClient.convertToType(data['postalDeliveryNumber'], 'Number');
      }
      if (data.hasOwnProperty('postalDeliveryNumberPrefix')) {
        obj['postalDeliveryNumberPrefix'] = ApiClient.convertToType(data['postalDeliveryNumberPrefix'], 'String');
      }
      if (data.hasOwnProperty('postalDeliveryNumberSuffix')) {
        obj['postalDeliveryNumberSuffix'] = ApiClient.convertToType(data['postalDeliveryNumberSuffix'], 'String');
      }
      if (data.hasOwnProperty('localityName')) {
        obj['localityName'] = ApiClient.convertToType(data['localityName'], 'String');
      }
      if (data.hasOwnProperty('postcode')) {
        obj['postcode'] = ApiClient.convertToType(data['postcode'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique identifier for an address as defined by Australia Post.  Also known as Delivery Point Identifier
   * @member {String} dpid
   */
  exports.prototype['dpid'] = undefined;
  /**
   * Thoroughfare number for a property (first number in a property ranged address)
   * @member {Number} thoroughfareNumber1
   */
  exports.prototype['thoroughfareNumber1'] = undefined;
  /**
   * Suffix for the thoroughfare number. Only relevant is thoroughfareNumber1 is populated
   * @member {String} thoroughfareNumber1Suffix
   */
  exports.prototype['thoroughfareNumber1Suffix'] = undefined;
  /**
   * Second thoroughfare number (only used if the property has a ranged address eg 23-25)
   * @member {Number} thoroughfareNumber2
   */
  exports.prototype['thoroughfareNumber2'] = undefined;
  /**
   * Suffix for the second thoroughfare number. Only relevant is thoroughfareNumber2 is populated
   * @member {String} thoroughfareNumber2Suffix
   */
  exports.prototype['thoroughfareNumber2Suffix'] = undefined;
  /**
   * Unit number (including suffix, if applicable)
   * @member {String} flatUnitNumber
   */
  exports.prototype['flatUnitNumber'] = undefined;
  /**
   * Floor or level number (including alpha characters)
   * @member {String} floorLevelNumber
   */
  exports.prototype['floorLevelNumber'] = undefined;
  /**
   * Allotment number for the address
   * @member {Number} lotNumber
   */
  exports.prototype['lotNumber'] = undefined;
  /**
   * Building/Property name 1
   * @member {String} buildingName1
   */
  exports.prototype['buildingName1'] = undefined;
  /**
   * Building/Property name 2
   * @member {String} buildingName2
   */
  exports.prototype['buildingName2'] = undefined;
  /**
   * The name of the street
   * @member {String} streetName
   */
  exports.prototype['streetName'] = undefined;
  /**
   * The street type. Valid enumeration defined by Australia Post PAF code file
   * @member {String} streetType
   */
  exports.prototype['streetType'] = undefined;
  /**
   * The street type suffix. Valid enumeration defined by Australia Post PAF code file
   * @member {String} streetSuffix
   */
  exports.prototype['streetSuffix'] = undefined;
  /**
   * Postal delivery type. (eg. PO BOX). Valid enumeration defined by Australia Post PAF code file
   * @member {String} postalDeliveryType
   */
  exports.prototype['postalDeliveryType'] = undefined;
  /**
   * Postal delivery number if the address is a postal delivery type
   * @member {Number} postalDeliveryNumber
   */
  exports.prototype['postalDeliveryNumber'] = undefined;
  /**
   * Postal delivery number prefix related to the postal delivery number
   * @member {String} postalDeliveryNumberPrefix
   */
  exports.prototype['postalDeliveryNumberPrefix'] = undefined;
  /**
   * Postal delivery number suffix related to the postal delivery number
   * @member {String} postalDeliveryNumberSuffix
   */
  exports.prototype['postalDeliveryNumberSuffix'] = undefined;
  /**
   * Full name of locality
   * @member {String} localityName
   */
  exports.prototype['localityName'] = undefined;
  /**
   * Postcode for the locality
   * @member {String} postcode
   */
  exports.prototype['postcode'] = undefined;
  /**
   * State in which the address belongs. Valid enumeration defined by Australia Post PAF code file
   * @member {String} state
   */
  exports.prototype['state'] = undefined;



  return exports;
}));


