/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openbanking.client.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The list of available product categories for categorising products and accounts
 */
@JsonAdapter(EnumProductCategory.Adapter.class)
public enum EnumProductCategory {
  
  PERS_AT_CALL_DEPOSITS("PERS_AT_CALL_DEPOSITS"),
  
  BUS_AT_CALL_DEPOSITS("BUS_AT_CALL_DEPOSITS"),
  
  TERM_DEPOSITS("TERM_DEPOSITS"),
  
  RESIDENTIAL_MORTGAGES("RESIDENTIAL_MORTGAGES"),
  
  PERS_CRED_AND_CHRG_CARDS("PERS_CRED_AND_CHRG_CARDS"),
  
  BUS_CRED_AND_CHRG_CARDS("BUS_CRED_AND_CHRG_CARDS"),
  
  PERS_LOANS("PERS_LOANS"),
  
  PERS_LEASING("PERS_LEASING"),
  
  BUS_LEASING("BUS_LEASING"),
  
  TRADE_FINANCE("TRADE_FINANCE"),
  
  PERS_OVERDRAFT("PERS_OVERDRAFT"),
  
  BUS_OVERDRAFT("BUS_OVERDRAFT"),
  
  BUS_LOANS("BUS_LOANS"),
  
  FOREIGN_CURR_AT_CALL_DEPOSITS("FOREIGN_CURR_AT_CALL_DEPOSITS"),
  
  FOREIGN_CURR_TERM_DEPOSITS("FOREIGN_CURR_TERM_DEPOSITS"),
  
  FOREIGN_CURR_LOAN("FOREIGN_CURR_LOAN"),
  
  FOREIGN_CURRRENCT_OVERDRAFT("FOREIGN_CURRRENCT_OVERDRAFT"),
  
  TRAVEL_CARD("TRAVEL_CARD");

  private String value;

  EnumProductCategory(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EnumProductCategory fromValue(String text) {
    for (EnumProductCategory b : EnumProductCategory.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }

  public static class Adapter extends TypeAdapter<EnumProductCategory> {
    @Override
    public void write(final JsonWriter jsonWriter, final EnumProductCategory enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EnumProductCategory read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EnumProductCategory.fromValue(String.valueOf(value));
    }
  }
}

